channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=22.0.3
- pip:
  - mlflow==2.11.1
  - cffi==1.15.0
  - click==8.0.3
  - cloudpickle==2.0.0
  - colorama==0.4.6
  - cupy-cuda115==9.6.0
  - cython==0.29.24
  - defusedxml==0.7.1
  - distributed==2021.11.2
  - importlib-metadata==6.11.0
  - jinja2==3.0.3
  - lightgbm==4.3.0
  - matplotlib==3.5.0
  - numpy==1.24.4
  - packaging==21.3
  - pandas==1.5.3
  - pyarrow==5.0.0
  - pynvml==11.4.1
  - pyyaml==6.0
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - setproctitle==1.3.3
  - xxhash==3.4.1
name: mlflow-env
