channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=22.0.3
- pip:
  - mlflow
  - cffi==1.15.0
  - cloudpickle==2.0.0
  - colorama==0.4.6
  - cupy-cuda115==9.6.0
  - cython==0.29.24
  - defusedxml==0.7.1
  - distributed==2021.11.2
  - ipython==7.31.1
  - lightgbm==4.3.0
  - matplotlib==3.5.0
  - pyarrow==5.0.0
  - pynvml==11.4.1
  - scikit-learn==1.2.2
  - setproctitle==1.3.3
  - xxhash==3.4.1
name: mlflow-env
